#include "common.h"

/* magic number to identify keystroke generated by this program */
ULONG_PTR MAGIC;

enum {
    UP,
    DOWN
} state;
ULONGLONG time;

LRESULT CALLBACK LowLevelKeyboardProc(int nCode, WPARAM wParam, LPARAM lParam)
{
    if (nCode != HC_ACTION)
        return CallNextHookEx(0, nCode, wParam, lParam);

    KBDLLHOOKSTRUCT* lparam = (KBDLLHOOKSTRUCT*)lParam;

    if (lparam->dwExtraInfo == MAGIC)
        return CallNextHookEx(0, nCode, wParam, lParam);

    if (lparam->vkCode == VK_OEM_7 && wParam == WM_KEYDOWN) {
        press(VK_RCONTROL, 0);
        return 1;
    } else if (lparam->vkCode == VK_OEM_7 && wParam == WM_KEYUP) {
        release(VK_RCONTROL, 0);
        return 1;
    }

    if (state == UP) {
        if (lparam->vkCode == VK_RCONTROL && wParam == WM_KEYDOWN) {
            state = DOWN;
            time = time_now_milliseconds();
        }
    } else {
        int cond = (lparam->vkCode == VK_RCONTROL && wParam == WM_KEYUP
                    && time_now_milliseconds() - time < 300);

        if (lparam->vkCode == VK_RCONTROL && wParam == WM_KEYDOWN)
            ;
        else
            state = UP;

        if (cond) {
            release(VK_RCONTROL, MAGIC);
            press(VK_OEM_7, MAGIC);
            release(VK_OEM_7, MAGIC);
            return 1;
        }
    }

    return CallNextHookEx(0, nCode, wParam, lParam);
}

int main(void)
{
    CreateMutexA(NULL, FALSE, "WKU_" __FILE__ "_INSTANCE");
    if (GetLastError() == ERROR_ALREADY_EXISTS)
        return 1;

    FreeConsole();

    MAGIC = naive_hash(__FILE__);

    SetWindowsHookEx(WH_KEYBOARD_LL, LowLevelKeyboardProc, NULL, 0);

    MSG msg;
    GetMessage(&msg, NULL, 0, 0);
}
