#include "common.h"

/* magic number to identify keystroke generated by this program */
ULONG_PTR MAGIC;

WORD MODIFIER = VK_TAB;

#define MAX_LEN 4
int EXIT[256] = { 0 };
WORD MAP[256][MAX_LEN] = { 0 };

enum {
    IDLE,
    PREPARED,
    MAPPING
} state;

int mapping[256] = { 0 };

LRESULT CALLBACK LowLevelKeyboardProc(int nCode, WPARAM wParam, LPARAM lParam)
{
    if (nCode != HC_ACTION)
        return CallNextHookEx(0, nCode, wParam, lParam);

    KBDLLHOOKSTRUCT* lparam = (KBDLLHOOKSTRUCT*)lParam;

    if (lparam->dwExtraInfo == MAGIC)
        return CallNextHookEx(0, nCode, wParam, lParam);

    switch (state) {
        case IDLE:
            if (lparam->vkCode == MODIFIER && (wParam == WM_KEYDOWN || wParam == WM_SYSKEYDOWN)) {
                state = PREPARED;
                return 1;
            }
            break;

        case PREPARED:
            if (EXIT[lparam->vkCode] && (wParam == WM_KEYUP || wParam == WM_SYSKEYUP)) {
                state = IDLE;
                press(MODIFIER, MAGIC);
                break;
            }

            if (MAP[lparam->vkCode][0] && (wParam == WM_KEYDOWN || wParam == WM_SYSKEYDOWN)) {
                state = MAPPING;
                /* fallthrough */
            } else {
                break;
            }

        case MAPPING:
            if (lparam->vkCode == MODIFIER && (wParam == WM_KEYUP || wParam == WM_SYSKEYUP)) {
                state = IDLE;
                return 1;
            }

            if (MAP[lparam->vkCode][0] && (wParam == WM_KEYDOWN || wParam == WM_SYSKEYDOWN)) {
                mapping[lparam->vkCode] = 1;
            }
    }

    if (mapping[lparam->vkCode]) {
        if (wParam == WM_KEYDOWN || wParam == WM_SYSKEYDOWN) {
            // HACK: N -> "Shift + Insert"
            if (lparam->vkCode == 'N') {
                press(VK_SHIFT, MAGIC);
                press(VK_OEM_7, MAGIC);
                release(VK_OEM_7, MAGIC);
                release(VK_SHIFT, MAGIC);
            }
            for (int idx = 0; idx < MAX_LEN; idx++) {
                if (MAP[lparam->vkCode][idx] == 0)
                    break;
                press(MAP[lparam->vkCode][idx], MAGIC);
            }
        } else if (wParam == WM_KEYUP || wParam == WM_SYSKEYUP) {
            for (int idx = MAX_LEN - 1; idx >= 0; idx--) {
                if (MAP[lparam->vkCode][idx] == 0)
                    continue;
                release(MAP[lparam->vkCode][idx], MAGIC);
            }
            // HACK: N -> "Shift + Insert"
            if (lparam->vkCode == 'N') {
                press(VK_SHIFT, MAGIC);
                press(VK_OEM_7, MAGIC);
                release(VK_OEM_7, MAGIC);
                release(VK_SHIFT, MAGIC);
            }
            mapping[lparam->vkCode] = 0;
        }
        return 1;
    }

    return CallNextHookEx(0, nCode, wParam, lParam);
}

int main(void)
{
    EXIT[MODIFIER] = 1;
    EXIT[VK_LCONTROL] = 1;
    EXIT[VK_LMENU] = 1;
    EXIT[VK_LSHIFT] = 1;
    EXIT[VK_LWIN] = 1;
    EXIT[VK_RCONTROL] = 1;
    EXIT[VK_RMENU] = 1;
    EXIT[VK_RSHIFT] = 1;
    EXIT[VK_RWIN] = 1;

    MAP[MODIFIER][0] = 1;
    MAP['0'][0] = VK_F10;
    MAP['1'][0] = VK_F1;
    MAP['2'][0] = VK_F2;
    MAP['3'][0] = VK_F3;
    MAP['4'][0] = VK_F4;
    MAP['5'][0] = VK_F5;
    MAP['6'][0] = VK_F6;
    MAP['7'][0] = VK_F7;
    MAP['8'][0] = VK_F8;
    MAP['9'][0] = VK_F9;
    MAP['E'][0] = VK_VOLUME_UP;
    MAP['F'][0] = VK_LWIN;
    MAP['H'][0] = VK_LEFT;
    MAP['I'][0] = VK_PRIOR;
    MAP['J'][0] = VK_DOWN;
    MAP['K'][0] = VK_UP;
    MAP['L'][0] = VK_RIGHT;
    MAP['M'][0] = VK_SHIFT;
    MAP['M'][1] = VK_INSERT;
    MAP['N'][0] = VK_SHIFT;
    MAP['N'][1] = VK_INSERT;
    MAP['P'][0] = VK_SNAPSHOT;
    MAP['Q'][0] = VK_VOLUME_MUTE;
    MAP['U'][0] = VK_NEXT;
    MAP['W'][0] = VK_VOLUME_DOWN;
    MAP[VK_BACK][0] = VK_DELETE;
    MAP[VK_OEM_COMMA][0] = VK_HOME;
    MAP[VK_OEM_MINUS][0] = VK_F11;
    MAP[VK_OEM_PERIOD][0] = VK_END;
    MAP[VK_OEM_PLUS][0] = VK_F12;

    CreateMutexA(NULL, FALSE, "WKU_" __FILE__ "_INSTANCE");
    if (GetLastError() == ERROR_ALREADY_EXISTS)
        return 1;

    FreeConsole();

    MAGIC = naive_hash(__FILE__);

    SetWindowsHookEx(WH_KEYBOARD_LL, LowLevelKeyboardProc, NULL, 0);

    MSG msg;
    GetMessage(&msg, NULL, 0, 0);
}
