#include "common.h"

WORD MODIFIER = VK_OEM_3; /* ~ */

/* magic number to identify keystroke generated by this program */
ULONG_PTR MAGIC;

enum {
    IDLE,
    PREPARED,
    MAPPING
} state;

WORD map(WORD vkCode)
{
    switch (vkCode) {
        case 'H':
            return VK_LEFT;
        case 'J':
            return VK_DOWN;
        case 'K':
            return VK_UP;
        case 'L':
            return VK_RIGHT;
        case 'U':
            return VK_NEXT;
        case 'I':
            return VK_PRIOR;
    }
    return 0;
}

void release_all()
{
    release(VK_LEFT, MAGIC);
    release(VK_DOWN, MAGIC);
    release(VK_UP, MAGIC);
    release(VK_RIGHT, MAGIC);
    release(VK_NEXT, MAGIC);
    release(VK_PRIOR, MAGIC);
}

LRESULT CALLBACK LowLevelKeyboardProc(int nCode, WPARAM wParam, LPARAM lParam)
{
    if (nCode != HC_ACTION)
        return CallNextHookEx(0, nCode, wParam, lParam);

    KBDLLHOOKSTRUCT* lparam = (KBDLLHOOKSTRUCT*)lParam;

    if (lparam->dwExtraInfo == MAGIC)
        return CallNextHookEx(0, nCode, wParam, lParam);

    if (lparam->vkCode == MODIFIER && wParam == WM_KEYDOWN) {
        if (state == IDLE) {
            state = PREPARED;
        }
        return 1;
    } else if (lparam->vkCode == MODIFIER && wParam == WM_KEYUP) {
        if (state == PREPARED) {
            release_all();
            press(MODIFIER, MAGIC);
            release(MODIFIER, MAGIC);
        }
        state = IDLE;
        return 1;
    }

    if (state == PREPARED || state == MAPPING) {
        WORD map_vkCode = map(lparam->vkCode);
        if (map_vkCode) {
            state = MAPPING;
            if (wParam == WM_KEYDOWN) {
                press(map_vkCode, MAGIC);
                return 1;
            } else {
                release(map_vkCode, MAGIC);
                return 1;
            }
        }
    }

    return CallNextHookEx(0, nCode, wParam, lParam);
}

int main(void)
{
    CreateMutexA(NULL, FALSE, "WKU_" __FILE__ "_INSTANCE");
    if (GetLastError() == ERROR_ALREADY_EXISTS)
        return 1;

    FreeConsole();

    MAGIC = naive_hash(__FILE__);

    SetWindowsHookEx(WH_KEYBOARD_LL, LowLevelKeyboardProc, NULL, 0);

    MSG msg;
    GetMessage(&msg, NULL, 0, 0);
}
